project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('user/', include('user.urls')), 
    path('', include('user.urls')), 
]

user/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views

app_name = 'user'

urlpatterns = [
    path('', views.home, name=''),
    path('login/', views.login_user, name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('plataforma/', views.plataforma, name='plataforma'),
    path('logout/', views.logout_user, name='logout'),
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required


def home(request):
    return render(
        request,
        'home/home.html'
    )

def cadastro(request):
    print(request.method)

    if request.method == 'GET':
        return render(
            request,
            'home/cadastro.html'
            )
    # print(request.POST)
    username = request.POST.get('user')
    email = request.POST.get('email')
    senha = request.POST.get('password')
    print(f'Nome: {username}, \nEmail: {email}, \nPassword: {senha}')

    user = User.objects.filter(username=username).first()
    if user:
        return HttpResponse("Este usuario ja existe")
    
    user = User.objects.create_user(username=username, email=email, password=senha)
    user.save()

    return HttpResponseRedirect('/login')
    return HttpResponse("Cadastro realizado com sucesso")

    print(user)

def login_user(request):
    if request.method == 'GET':
        return render(
            request,
            'home/login.html'
        )

    username = request.POST.get('user')
    senha = request.POST.get('password')
    
    print(username, senha)
    user = authenticate(username=username, password=senha)
    if user:
        login(request, user)
        return render(
            request,
            'templates/login_success.html'
        )
    return HttpResponse("Não foi possivel realizar o login")

# so sera diresionado se estiver logado
# @login_required
def plataforma(request):
    if request.user.is_authenticated:
        return HttpResponse("Usuário logados com sucesso")
    return HttpResponse("E necessario estar logado")

# @login_required
def logout_user(request):
    if not(request.user.is_authenticated):
        return HttpResponse("Para usar o método 'deslogar' e necessario estar logado")
    logout(request)
    return HttpResponseRedirect('/login')

base/templates/login_success.html
<h1>Sucesso</h1>

user/templates/home/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <article class="form_register">
        <form action="#" class="cards" method="POST">{% csrf_token %}
            <div class="title-user">
                <h2>Register Usuario</h2>
            </div>
            <div class="card">
                <label for="user">Usuario</label>
                <input type="text" id="user" placeholder="Seu nome"  name="user" required>
            </div>
            <div class="card">
                <label for="user">E-mail</label>
                <input type="email" id="user" placeholder="Seu e-mail"  name="email" required>
            </div>
            <div class="card">
                <label for="password">Password</label>
                <input type="password" id="password" placeholder="Sua senha"  name="password">
            </div>
            <div class="login">
                <a href="{% url 'user:login' %}">login</a>
            </div>
            <div class="div-btn">
                <input type="submit" value="enviar" class="btn">
            </div>
        </form>
    </article>
</body>
</html>

user/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/css/login_user.css' %}">
    <title>Document</title>
</head>
<body>
    <section class="home">
        <div class="cont-login">
            <a href="{% url 'user:login' %}">Login</a>

            <a href="{% url 'user:cadastro' %}">Cadastro</a>
        </div>
        <div class="test_login">
            <a href="{% url 'user:plataforma' %}">Teste de login</a>
        </div>
        <div class="test_login logout">
            <a href="{% url 'user:logout' %}">logout</a>
        </div>
    </section>
</body>
</html>

user/templates/home/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <article class="form_register">
        <form action="#" class="cards" method="POST">{% csrf_token %}
            <div class="title-user">
                <h2>login Usuario</h2>
            </div>
            <div class="card">
                <label for="user">Usuario</label>
                <input type="text" id="user" placeholder="Seu nome"  name="user" required>
            </div>
            <div class="card">
                <label for="password">Password</label>
                <input type="password" id="password" placeholder="Sua senha"  name="password">
            </div>
            <div class="cadastro">
                <a href="{% url 'user:cadastro' %}">Cadastro</a>
            </div>
            <div class="div-btn">
                <input type="submit" value="enviar" class="btn">
            </div>
        </form>
    </article>
</body>
</html>